### ISSUE TITLE
Cannot resolve module 'angular2-meteor-client'

### ISSUE THREAD

**Issue by mjwheatley** [Muffasa/ionic2-meteor-starter#2]
mjwheatley:~/Development/Tanoshii/Ionic2/ionic2-meteor-starter$ ionic serve

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-framework/fonts/*_/_.ttf

∆ Copying HTML
√ Matching patterns: app/*_/_.html

√ Sass compilation complete
√ HTML copied to www/build
√ Fonts copied to www/build/fonts

./app/app.ts
Module build failed: Error: Cannot resolve module 'angular2-meteor-client' in /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/app/pages/page2
    Required in /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/app/pages/page2/page2.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/dist.babel/deps.js:482:88)
    at /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/dist.babel/deps.js:301:37
    at tryCatcher (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/catch_filter.js:52:40)
    at CatchFilter.tryCatcher (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)
 @ multi main,[default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/angular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.,[default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:70
Cannot find namespace 'core'.,[default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:82
Cannot find namespace 'core'.,[default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:115
Cannot find namespace 'core'.,[default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/ionic2-meteor/ionic2-meteor.d.ts:5:46
Cannot find namespace 'core'. (CLI v2.0.0-beta.17)

---

I tried messing with the typings but I could not get this working.
Is it possible to reference the typings that seem to be working in the meteor-core?

**Comment by ohadgk** [comment]
there will be a simple typing references when ill integrate webpack to controll the build process.
untill then this error shouldt break anything and the transpile should be seccessful, if the transpile breaks let me know.

**Comment by mjwheatley** [comment]
I'm confused.  If this error shouldn't break anything, why doesn't the module build.  Currently I am unable to build and run this project.  I have install the prerequisites mentioned (Ionic CLI, Meteor 1.2, and TSD).  

**System Information:**
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.4
Xcode version: Xcode 7.2.1 Build version 7C1002

Is there something else I need to configure or setup to get this project to run?

**Comment by adowning** [comment]
Exact same problem here.  Ionic will not finish the serve process when this module fails.

**Comment by ohadgk** [comment]
npm version must be grater then 3.
Remove the node_modules directory, install node 5.x and run npm install again (make sure npm -v is larger then 3).

The ionic serve command failed because the webpack transpile failed: 
the line `import {MeteorComponent} from 'angular2-meteor-client';` transpiled to require('angular2-meteor-client') if no module with that name already declared. So on npm 3 and down the dependencies of each package is nested inside that package node_modules directory, on npm 3 and above all the dependencies installed on the root node_modules directory allowing the require('angular2-meteor-client') to find the lib.

For more details about the change of npm3.x read [this](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging).
Let me know if the webpack build failed when npm install with npm 3.x.
Thanks.

**Comment by mjwheatley** [comment]
I successfully updated to node v5.7.1 and npm v3.8.0.  I confirm that the application now starts despite the following errors.

ERROR in [default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/node_modules/angular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.

ERROR in [default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:70
Cannot find namespace 'core'.

ERROR in [default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:82
Cannot find namespace 'core'.

ERROR in [default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/angular2-meteor.d.ts:11:115
Cannot find namespace 'core'.

ERROR in [default] /Users/mjwheatley/Development/Tanoshii/Ionic2/ionic2-meteor-starter/typings/ionic2-meteor/ionic2-meteor.d.ts:5:46
Cannot find namespace 'core'.

√ Webpack complete

∆ Starting dev server.

√ Running live reload server: http://localhost:35729
√ Running dev server:  http://localhost:8100
√ Watching: 0=www/build/**/*.html, 1=www/build/**/_.js, 2=www/build/__/_.css
